# Generated by Django 3.1.2 on 2020-11-26 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advisor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='team',
            new_name='Sheet_model',
        ),
    ]
