# Generated by Django 3.1.2 on 2020-11-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advisor', '0002_auto_20201126_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheet_model',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
